name: 'Publish Allure Report'
description: 'Generate and publish Allure test reports as artifacts'
runs:
  using: 'composite'
  steps:
    - name: Install Allure
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
          rm allure-2.24.0.tgz
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install allure
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          choco install allure-commandline -y
        fi
        allure --version

    - name: Check Allure Results
      shell: bash
      run: |
        echo "Checking for Allure results..."
        if [ -d "target/allure-results" ] && [ -n "$(ls -A target/allure-results 2>/dev/null)" ]; then
          echo "✓ Allure results found in target/allure-results:"
          ls -la target/allure-results/ | head -20
          echo "Total files: $(find target/allure-results -type f | wc -l)"
        else
          echo "⚠️  No Allure results found in target/allure-results"
          echo "Listing target directory contents:"
          ls -la target/ 2>/dev/null || echo "target directory does not exist"
        fi

    - name: Generate Allure Report (Maven)
      shell: bash
      run: |
        mvn allure:report --no-transfer-progress

    - name: Generate Allure Report (CLI)
      shell: bash
      run: |
        if [ ! -d "target/allure-results" ] || [ -z "$(ls -A target/allure-results 2>/dev/null)" ]; then
          echo "⚠️  No Allure results to generate report from (CLI)"
          exit 0
        fi
        allure generate target/allure-results -o target/allure-report --clean
        echo "Allure report generated successfully (CLI)"

    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/allure-report
        retention-days: 30
        if-no-files-found: ignore

    - name: Upload Allure Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: target/allure-results
        retention-days: 7
        if-no-files-found: ignore
